build:
    environment:
        php:
            version: 5.5.25
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover report.xml'
                coverage:
                    file: 'report.xml'
                    format: 'clover'
