build:
    environment:
        php:
            version: 5.5.25
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=report'
                coverage:
                    file: 'report'
                    format: 'clover'
