language: php
cache:
  directories:
    - $HOME/.composer/cache
matrix:
    include:
        - php: 7.4
          env: deps=low
        - php: 8.0
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly
before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer update --prefer-dist; fi
