language: php
cache:
  directories:
    - $HOME/.composer/cache
matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly
before_script:
  - composer update
